### ISSUE TITLE
TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by mwoodpatrick** [vercel/next-learn-starter#35]
When building I'm getting the following error with latest packages and node v16.2.0 (npm v7.13.0)

TypeError: Class extends value undefined is not a constructor or null
    at Object.618 (/home/mwoodpatrick/projects/git/www/nextjs-wp/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:100)
    at __nccwpck_require__ (/home/mwoodpatrick/projects/git/www/nextjs-wp/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11843)
    at Object.270 (/home/mwoodpatrick/projects/git/www/nextjs-wp/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:413)
    at __nccwpck_require__ (/home/mwoodpatrick/projects/git/www/nextjs-wp/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11843)

    at Object.327 (/home/mwoodpatrick/projects/git/www/nextjs-wp/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:260)
    at __nccwpck_require__ (/home/mwoodpatrick/projects/git/www/nextjs-wp/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11843)
    at Object.845 (/home/mwoodpatrick/projects/git/www/nextjs-wp/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:3733)
    at __nccwpck_require__ (/home/mwoodpatrick/projects/git/www/nextjs-wp/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11843)
    at /home/mwoodpatrick/projects/git/www/nextjs-wp/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11971
    at Object.<anonymous> (/home/mwoodpatrick/projects/git/www/nextjs-wp/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11997)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)

**Comment by leerob** [comment]
Is your code identical to the working examples here?

**Comment by mwoodpatrick** [comment]
I had added more modules but recreating package-lock.json and node_modules fixed my problem and I was able to deploy to Vercel

**Comment by bayram00** [comment]
i have a problem like this too


error - Error [TypeError]: Class extends value undefined is not a constructor or null
    at ../../node_modules/.pnpm/undici@5.11.0/node_modules/undici/lib/fetch/file.js (evalmachine.<anonymous>:5724:19)
    at __require (evalmachine.<anonymous>:14:50)
    at ../../node_modules/.pnpm/undici@5.11.0/node_modules/undici/lib/fetch/formdata.js (evalmachine.<anonymous>:5881:49)
    at __require (evalmachine.<anonymous>:14:50)
    at ../../node_modules/.pnpm/undici@5.11.0/node_modules/undici/lib/fetch/body.js (evalmachine.<anonymous>:6094:35)
    at __require (evalmachine.<anonymous>:14:50)
    at ../../node_modules/.pnpm/undici@5.11.0/node_modules/undici/lib/fetch/response.js (evalmachine.<anonymous>:6510:49)
    at __require (evalmachine.<anonymous>:14:50)
    at <unknown> (evalmachine.<anonymous>:11635:30)
    at requireFn (file://C:\Users\Bayram\Desktop\nextapi\node_modules\next\dist\compiled\edge-runtime\index.js:1:7079) {
  middleware: true

**Comment by fernandolucchesi** [comment]
> i have a problem like this too
> 
> error - Error [TypeError]: Class extends value undefined is not a constructor or null at ../../node_modules/.pnpm/undici@5.11.0/node_modules/undici/lib/fetch/file.js (evalmachine.:5724:19) at __require (evalmachine.:14:50) at ../../node_modules/.pnpm/undici@5.11.0/node_modules/undici/lib/fetch/formdata.js (evalmachine.:5881:49) at __require (evalmachine.:14:50) at ../../node_modules/.pnpm/undici@5.11.0/node_modules/undici/lib/fetch/body.js (evalmachine.:6094:35) at __require (evalmachine.:14:50) at ../../node_modules/.pnpm/undici@5.11.0/node_modules/undici/lib/fetch/response.js (evalmachine.:6510:49) at __require (evalmachine.:14:50) at (evalmachine.:11635:30) at requireFn (file://C:\Users\Bayram\Desktop\nextapi\node_modules\next\dist\compiled\edge-runtime\index.js:1:7079) { middleware: true

same, happening after upgraded to next 13

**Comment by fernandolucchesi** [comment]
> i have a problem like this too
> 
> error - Error [TypeError]: Class extends value undefined is not a constructor or null at ../../node_modules/.pnpm/undici@5.11.0/node_modules/undici/lib/fetch/file.js (evalmachine.:5724:19) at __require (evalmachine.:14:50) at ../../node_modules/.pnpm/undici@5.11.0/node_modules/undici/lib/fetch/formdata.js (evalmachine.:5881:49) at __require (evalmachine.:14:50) at ../../node_modules/.pnpm/undici@5.11.0/node_modules/undici/lib/fetch/body.js (evalmachine.:6094:35) at __require (evalmachine.:14:50) at ../../node_modules/.pnpm/undici@5.11.0/node_modules/undici/lib/fetch/response.js (evalmachine.:6510:49) at __require (evalmachine.:14:50) at (evalmachine.:11635:30) at requireFn (file://C:\Users\Bayram\Desktop\nextapi\node_modules\next\dist\compiled\edge-runtime\index.js:1:7079) { middleware: true

Upgrading node fixes this. Check: https://github.com/vercel/next.js/issues/42729

**Comment by maniatoffl** [comment]
Updating Node version didn't work for me, I had to remove next 13 `middleware.ts` under `src` folder, and created custom server.js for handling middlewares. The issue then resolved for me .

**Comment by eichgi** [comment]
@maniatoffl It seems you need to use node v16.4 at least in order to use a middleware.ts file as I did. 

Source: https://stackoverflow.com/questions/74739282/next-js13-middleware-occurs-typeerror-class-extends-value-undefined-is-not-a-c
